name: Telegram Notification

on: [push, pull_request]

jobs:
  build:
    name: Notification
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Send Notification in Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_RECIEVER }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
