name: Telegram Notification

on: [push, pull_request]

jobs:
  build:
    name: Notification
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Send Notification in Telegram
      uses: appleboy/telegram-action@master
      if: github.event_name == 'push'
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
